version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - mongo-compose-network

#validar como seria o mongo express e o pgadmin
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
    links:
      - mongodb
    networks:
      - mongo-compose-network

  jenkins:
    image: jenkins/jenkins:lts  # Usa a versão LTS (Long Term Support) do Jenkins
    container_name: jenkins
    ports:
      - "8080:8080"  # Porta para a interface web do Jenkins
      - "50000:50000"  # Porta para comunicação com agentes (nodes) do Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://localhost:8080
    restart: unless-stopped

  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    networks:
      - postgres-compose-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  # Grafana (Visualização de métricas)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus

  # Prometheus (Coleta de métricas)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # Zookeeper (necessário para o Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"  # Porta para a interface web do Metabase
    environment:
      MB_DB_TYPE: postgres  # Tipo de banco de dados para o Metabase (opcional)
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: example
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  mongo-compose-network:
    driver: bridge
  postgres-compose-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
  jenkins_home:
  pgadmin_data:
  grafana_data:
  prometheus_data:
  pentaho_data:
  metabase_data: